- docs/get-started.md
- docusaurus.config.js
- src/pages/index.js
Changed the partner signup link to the new form powered by Marketo: https://start.paloaltonetworks.com/become-a-technology-partner
> changed the partner sign up page link to the Marketo powered form

- docs/why-demisto.mdx
Link was incorrectly visualized and was broken. Also changed it to a button
> Fixed the 'Get Started Now' link in the 'Why Demisto' page

- package-lock.json
- package.json
- static/doc_imgs/.gitinclude
In Hold (pending review)
N/A
Images referenced in markdown using relative path break in certain scenarios, such as when a trailing slash is added.
Updated build script to copy assets to `static/doc_imgs` directory and update all markdown `img` references prior to build. The intended effect is that all `img` references will point to the public `/doc_imgs` URL instead of the relative path.
> Fix broken assets

- src/css/custom.css
Ready for review
fixes: Addresses issue mentioned in #34 
Added custom CSS to darken the search bar text color and lighten background in dark mode.
(Note that Prettier performed additional minor formatting changes to the CSS)
> Change navbar search input and background color in dark mode

- docs/integrations/code-conventions.md
Fixes: https://github.com/demisto/content-docs/issues/65
Ready
fixes: https://github.com/demisto/content-docs/issues/65
Fixes link to Hello World in code conventions
Also fixes trailing backslash in first paragraph
> Fixed broken link on code-conventions

- docs/integrations/context-and-outputs.md
Ready
Updated the context outputs doc, according to our latest decision, to pass the API response as is to the context without modifying it.
> Update context outputs doc

- content-repo/create-docs.sh
- content-repo/gendocs.py
Ready
When building a PR preview and there is no matching branch we generate a smaller reference doc build with only 20 files if the only modifications are in the docs dir. 
Note that this build will still generate a full reference as it includes modifications outside of the docs dir. Only after we merge to master will we see the effects of this.
> optimize build so on pr we build a preview of reference docs

- content-repo/create-docs.sh
Ready
We were checking out the content repo using git-lfs. This is now disabled as the files are not needed.
> disable git-lfs when checking out content repo

- docs/concepts/design-best-practices.md
I've updated the design guidelines. 
- added the naming convention of the commands where we put the object first and then the action
- added the note about the indicator timeline. is the message clear? too simple? 
Guys go over it tell me what do you think, I would love your feedback.
> Design Guidelines Edit - around command naming convention and indicator timeline 

- docs/integrations/changelog.md
Ready
fixes: Internal change to documentation procedure
Documented the ability to comment out sections of release notes.
> Document ability to comment out sections of release notes.

- content-repo/gendocs.py
Ready
Fix the way we escape the name of ref pages
Before:
After:
> Ref docs: change escaping logic for name. only do html escape when on page

- docusaurus.config.js
Ready
n/a
Filters Algolia search results by `type` attribute which represents what hierarchy the search result occupies on a doc page. The goal is to help narrow the search results by excluding subheadings.
@glicht please test and provide feedback.
Note: The `type` attribute was added as a filterable facet in preparation for this pull request. 
> Filter search results by type/hierarchy

- docusaurus.config.js
Ready
n/a
Allow results matching `type:content` to appear in search results. Please note that this change could result in many more hits.
> Add type:content to search filter

- docs/integrations/changelog.md
Ready
fixes: Internal
Added to https://xsoar.pan.dev/docs/integrations/changelog
> Add to documentation requirement of committing files before running update-release-notes command

- content-repo/gendocs.py
- content-repo/gendocs_test.py
Ready
Any content in DeprecatedContent will get a "Deprecated" callout. Mostly relevant for playbooks that don't have the yml setting of deprecated.
> add "Deprecated" callout to content from Packs/DeprecatedContent

- content-repo/extra-docs/releases/20.7.1.md
Ready
The header of the compatibility message was too big:
> reducing the header size of the compatibility message

- docusaurus.config.js
Ready
Added announcement bar at the top of the page to point to the content repo to star it (if they like it)
> add announcment bar for github star

- src/css/custom.css
Ready
n/a
Note admonition p text in dark mode was illegible due to CSS override. This solution introduces a slight change in text color throughout the site but there isn't a more specific CSS variable that covers admonition body text styling. Please review and let me know if you're ok with the changes.
Before:
After:
> Remove markdown p color CSS override

- docs/integrations/fetching-incidents.md
- docs/integrations/packs-format.md
Ready
Added .pack-ignore documentation
This file allows ignoring linter errors while lint checking and ignoring tests in the test collection.
To add ignored tests/linter errors in a file, first, add the file name to the **.pack-ignore** in this format
```
[file:integration-to-ignore.yml]
```
On the following line add `ignore=` flag, with one or more comma-separated values:
1. `auto-test` - ignore test file in the build test collection.
2. `linter code` e.g. IN126 - ignore linter error codes.
```
[file:playbook-Special-Test-Not-To-Run-Directly.yml]
ignore=auto-test
[file:integration-to-ignore.yml]
ignore=IN126,PA116
```
> Added .pack-ignore documentation

- content-repo/gendocs.py
Ready
cause of change done in https://github.com/demisto/content-docs/pull/335/commits/ceb94ee91b9fb03ce35b68ec709abe2611ac8741 the comparison done in versions to check if should add packs download link always come up as false
> use StrictVersion in version comparison in marketplace link

- docs/integrations/code-conventions.md
- docs/integrations/context-and-outputs.md
Ready
Updated descriptions to match new `CommandResults.indicator` changes, and emphasized `return_results` support for list of `CommandResults`.
> Deprecated CommandResults.indicators and added CommandResults.indicator

- docs/integrations/code-conventions.md
Ready
Added documentation of the new `ignore_auto_extract`  parameter in `CommandResults()`
Linked Content PR: https://github.com/demisto/content/pull/9874
> Added CommandResults autoextract documentation

- docs/integrations/mirroring.md
Ready
Adding a note regarding incident IDs returned by get-modified-remote-data.
Currently only incident IDs of type string are supported, therefore added a note
for it so developers reading this doc will know s/he needs to transform IDs to string
in case they are not string in order for get-modified-remote-data to work properly.
> Update mirroring.md - incident IDs returned by get-modified-remote-data must be of type str

- docusaurus.config.js
- genPackDetails.js
Ready
Start slice index at 0 instead of 1 to ensure `MAX_PACKS` results in accurate number of packs built.
> Start slice index at 0 instead of 1

- docs/contributing/marketplace.md
Ready
The link to the PANW documentation about contributing a content pack was dead - I updated the link to the Cortex XSOAR 6.1 version documentation which is live. I also fixed the incorrect grammar in the first note at the bottom of the page.
> Minor fixes to marketplace docs page

- src/theme/DocSidebar/index.js
Ready
Moved the siidebar to browser only rendering. The sidebar is not really needed for SEO and doing this improves the build by about 12 minutes. It does introduce a small delay (around 1 sec) until the sidebar is rendered in reference pages on first access. 
@sserrata @csestito please provide your feedback
> sidebar: browser only rendering

- genMarketplace.js
- src/css/custom.css
- src/theme/MarketplaceSidebar/index.js
Ready
Small change to address color/display issues with `alert--secondary` component. The new color was taken from the in-product XSOAR marketplace and can also be seen when viewing pack details pages (table border, version, et al.)
> Use brand palette for secondary color and fix markdown table formatting

- docs/integrations/code-conventions.md
Ready
refer to use the retry mechanism instead of sleep in the code conventions doc
> Code Conventions - add note about http call retries in the client section

- docs/integrations/scheduled-commands.md
Ready
https://github.com/demisto/etc/issues/37574
Added a section of the expected usage of `executeCommand` with `Scheduled Commands`
> Scheduled Command executeCommand section

- docs/integrations/yaml-file.md
Ready
The `execution` key in a yaml file marks a `potentially harmful`
> "execution" is "Potentially harmful"

- docs/documentation/release-notes.md
Ready
the examples we have for release notes are not properly formatted, specifically the ones for `Microsoft Graph Mail`:
pushed the examples to be in markdown
> Pack Release Notes - fmt markdown examples

- content-repo/extra-docs/packs/Prisma-Cloud.md
Ready
fixes: https://github.com/demisto/etc/issues/41825
The documentation currently does not explain why there are two classifiers and two mappers in Prisma Cloud app pack. It neither explains what is the purpose of each of them.
Added this information to the descriptions.
> Added classifiers descriptions to Prisma Cloud article

- package-lock.json
- package.json
Upgrade mini-css-extract-plugin version to fix the build-
see https://github.com/webpack/webpack/issues/14514
> Upgrade mini-css-extract-plugin version

- content-repo/extra-docs/packs/CoA-premium-pack-readme.md
refer correctly to unit42 feeds in courses of action docs
Ready
fixes: [link to the issue](https://github.com/demisto/content-docs/issues/816)
In Unit 42 Feed chapter, sentence shall be "The Courses of Action pack and playbooks work with both versions of the Unit 42 Feed pack." instead of "The Courses of Action pack and playbooks work with both versions of the MITRE ATT&CK pack."
> refer correctly to unit42 feeds

- .circleci/config.yml
Ready.
fixes: the last build failures.
this will fix the problem with exit status 137 (probably out of memory).
> replaced resource_class from large to xlarge

- src/theme/ContentPackTabs/styles.module.css
Ready
The button is a bit too right from where it's supposed to be. This PR fixes it.
How it should be:
How it actually is:
> Move Marketplace Download Button to the Left

- content-repo/gendocs_test.py
Ready
fixes: https://github.com/demisto/etc/issues/47753
Since we no longer release new content versions `test_process_release_doc` fails, as it relies on there being a release for the previous month.
This code should be mostly deprecated. For now, I updated the test to use the latest release notes that were created.
@glicht fyi
> Change test_process_release_doc to Use Static Version

- templates/details.hbs
Ready
fixes: [link to the issue](https://github.com/demisto/etc/issues/47848)
Fix the issue when `content-docs Download Packs Leads to Wrong Link When Trying To Download Packs With Hyphens.`
https://user-images.githubusercontent.com/71635916/162615487-4f92fd39-76a4-41e9-a8f0-26b17b35724a.mov
> fix the link

- docs/contributing/conventions.md
Ready
Since we delete the branch after the PR is merged, we have no need in the `git` history prior to opening the PR to be added onto the commits within the scope of the PR.
Makes it easier to load the PR and review it than than having to review [heavy commits such as this one](github.com/demisto/content/pull/18427/commits).
> added explanation how to squash commits

- templates/details.hbs
Ready
fixes: [link to the issue](https://jira-hq.paloaltonetworks.local/browse/CIAC-604)
In content upload flow, adding a new field the changelog.json called pullRequests, this is an array of numbers for the relevant PRs for the given version. This array is used in this repo to display the links. If the array is null or empty, nothing should be displayed
> Add pr numbers

- docs/documentation/readme_file.md
Ready
https://jira-hq.paloaltonetworks.local/browse/CIAC-3193
https://github.com/demisto/demisto-sdk/pull/1410
https://github.com/demisto/etc/issues/46444
Added note that relative image URLs are not supported in Pack documentation
> Relative Image URLs not supported in Pack READMEs

- content-repo/extra-docs/articles/CI-CD-Article.md
Ready
fixes: https://github.com/demisto/content-docs/issues/1138
the field "path" should not change as the automation workflow script relies on the path "repository"
for example the code below is from the configuration file.
```
PACKS_CHANGED=$(python $GITHUB_WORKSPACE/repository/build_related_scripts/get_modified_packs.py --repo_path $GITHUB_WORKSPACE/repository/)
```
https://github.com/demisto/content-ci-cd-template/blob/1a6ce4a4899281422d61272a98792a2a9fe0a20c/.github/workflows/config.yml#L38
changing "path" to anything else would result in "no such file or directory" error.
it should stay as
path: repository
> path: repository update

- genMarketplace.js
Ready
fixes: https://jira-hq.paloaltonetworks.local/browse/CIAC-3557
Add Wizard to supported content items, and use the provided content name when mapping is missing.
> Add support for wizard on marketplace page

- templates/details.hbs
fixes: https://jira-hq.paloaltonetworks.local/browse/CIAC-4235
There is no name in the indicator type json content. so we will use the `details` key as the name of the indicator type instead of the `name` key like in all other entities
An example how the json of an indicator type looks like
> use details instead of name in indicator type

- docs/concepts/dev-setup.md
- docs/contributing/checklist.md
- docs/contributing/contributing.md
- docs/tutorials/tut-design.md
- docs/welcome.md
Ready
Small fixes to broken links that I noticed.
Also fix formatting for [dev-setup](https://xsoar.pan.dev/docs/concepts/dev-setup) note. Currently markdown wasn't displayed properly:
> fix broken links + formatting

- content-repo/gendocs.py
Ready
fixes: https://jira-hq.paloaltonetworks.local/browse/CIAC-4779
Since we moved the marketplace to a new repo the contentDocsLinks file (which is in use in the marketplace repo) we upload the file to the bucket.
> upload content items links file to the bucket

- src/css/custom.css
Ready
fixes: https://jira-hq.paloaltonetworks.local/browse/CIAC-2190
Removed the URL in the CSS to show the arrows in dark mode
Before the fix:
After the fix:
> show arrows in dark mode

- docs/integrations/code-conventions.md
Ready
Fix unsafe code on the docs, which uses nested `.get()` without adding a default value of an empty dict (can result in a `None.get()` call, which leads to an exception).
Relevant docs section: https://xsoar.pan.dev/docs/integrations/code-conventions#credentials
> Add default value of an empty dict to nested `.get()` calls

- build_utils/slack_notifier.py
Ready
Removed the deprecated `as_user=False` arg from the slack notifier.
> fix slack notifier

- docs/integrations/scheduled-commands.md
Ready
raise_error_if_not_supported is no longer required, as all GA version of XSOAR support schedueld commands.
> Update Scheduled Command doc - remove raise_error_if_not_supported

- content-repo/gendocs.py
Ready
fixes: [Investigate why the gendocs script failed to create playbooks](https://jira-hq.paloaltonetworks.local/browse/CIAC-6197)
While failing the build as duplicates make sure that the duplicate fails are not from private repo.
> Ignore private docs form failing as duplicates

- docs/concepts/demisto-sdk.md
Ready
https://github.com/demisto/content-docs/pull/1334
Fixed typo demsito => demisto.
> Fix typo from demsito to demisto

- Pipfile
- Pipfile.lock
- content-repo/gendocs.py
Ready
Since there are some duplicate PB with the same ID as others ( deprecate and non-deprecate PB)
for example
[Deprecate PB](https://github.com/demisto/content/blob/master/Packs/BruteForce/Playbooks/Brute_Force_Investigation_-_Generic.yml)
[non-deprecated PB](https://github.com/demisto/content/blob/master/Packs/BruteForce/Playbooks/Brute_Force_Investigation_-_Generic_6_5.yml
)
We shouldn't fail the build on duplicate in such a case
> Change the failed duplicate only if the filename is the same

- content-repo/gendocs.py
Ready
fixes: https://jira-hq.paloaltonetworks.local/browse/CIAC-7009
Added a condition to update links file only on master. to avoid updating the file with only 20 links for each category when running on non-master branches.
> Update links file only on master

- docs/partners/become-a-tech-partner.md
Ready
fixes: https://jira-hq.paloaltonetworks.local/browse/CIAC-7383
Remove the TPA link from _Become a Tech Partner_ page.
> Remove TPA Link

- docs/integrations/fetching-incidents.md
In the SDK we have a validation that validates that the max_fetch and first_fetch params exist in the yml and the max_fetch has default value. It is necessary to add it to the fetch incident docs.
Ready
fixes: [link to the issue](https://jira-hq.paloaltonetworks.local/browse/CIAC-7371)
> Added the first_fetch and max_fetch to fetch-incidents docs

- .circleci/config.yml
- build_utils/slack_notifier.py
Ready
fixes:[ link to the issue](https://jira-hq.paloaltonetworks.local/browse/CIAC-6882)
Before this pr, the Build stage was sending message only on failure.
And the Deploy stage always.
Now, it will send on the Build stage also when there are failings on the "NPM Build content-repo docs" stage.
> [Slack Notifier] - Build stage will send on nightly the status

- content-repo/extra-docs/packs/Phishing-Campaign.md
Ready
fixes: https://jira-hq.paloaltonetworks.local/browse/CIAC-8096
Updated the phishing campaign article. Specifically:
- Added information about the **SetPhishingCampaignDetails** automation
- Added more information about the layout and how the dynamic sections work
- Added information to explain how similarity is updated
- Added a note explaining that the context in the Phishing Campaign incident should not be modified
- Added references and explanations about the Demisto Lock integration and how it's being used in the Detect & Manage Phishing Campaigns playbook
- Updated an old link to the phishing v2 playbook to point to the **Phishing - Generic v3** playbook
- Updated the available actions from the layout
> Updated the Phishing Campaign documentation

- docs/integrations/mirroring.md
Ready
`str` is unnecessary in a formatted string, `.keys()` in unnecessary in a call to `list`
> remove unnecessary calls

- docs/integrations/code-conventions.md
Ready
Fixes the key for demisto.results from Content to Contents. The function will not work as intended if the key is incorrect. Correct usage can be seen in the content repo: https://github.com/search?q=repo%3Ademisto%2Fcontent+demisto.results+contents&type=code
> Use the correct key for Contents

- .github/workflows/handle_new_contribution.yml
Ready
fixes: [link to the issue](https://jira-dc.paloaltonetworks.com/browse/CIAC-9038)
Added a new workflow that will assign the contributions TL to every new contribution PR in the content-docs repo.
> Handle new contribution

- docs/tutorials/tut-integration-ui.md
Ready
Fixing indentations for improved comprehension and readability.
> fixing ui integration tutorial

- content-repo/extra-docs/packs/palo-alto-networks-cortex-xdr---investigation-and-response.md
fixes: [link to the issue](https://jira-dc.paloaltonetworks.com/browse/CIAC-9678)
xdr lite playbooks Updated the pack Documentation.
> update xdr docs

- content-repo/extra-docs/articles/microsoft-auth-guide.md
> update docs for oproxy

- docs/concepts/vscode-extension.md
Mention WSL2 is required when running on Windows (Demisto-SDK requirement propogated)
> add WSL2 requirement

- docs/packs/packs-format.md
Added allowed values for `certification` filed
The allowed values are either "certified" or "verified".
(Validate PA118)
> [Content Packs Structure] Added Allowed Values For `certification`

- docs/packs/packs-format.md
In Progress
Some minor fixes to the Packs Format/Content Packs Structure doc including:
- Add/Remove inline code blocks when needed.
- Add titles to `.pack-ignore` and `.secrets-ignore` codeblocks.
- Fix typo in Pack metadata fields table. 
- Add links to approved categories, tags and use cases.
> Packs Format Update

- docs/integrations/code-conventions.md
Ready
https://jira-dc.paloaltonetworks.com/browse/CRTXDOC-2754
The heading in https://xsoar.pan.dev/docs/integrations/code-conventions#do-no-print-sensitive-data-to-the-log
should be 
Do Not Print Sensitive Data to the Log
> Fix typo in code-conventions.md

- docs/integrations/test-playbooks.md
related: [link](https://jira-dc.paloaltonetworks.com/browse/CIAC-10267) to the issue
demisto-sdk:  [PR](https://github.com/demisto/demisto-sdk/pull/4446) link
Added to the docs that when you create a test playbook you need to add the name of the TPB to the integration yml file.
> [Test Playbook] improve instructions

- docs/packs/packs-format.md
> Add defaultDataSource

- docs/tutorials/tut-setup-dev.md
fixes: [CIAC-10564](https://jira-dc.paloaltonetworks.com/browse/CIAC-10564)
In "Set Up Your Dev Environment" article, replace deprecated `demisto-sdk lint` command with the `demisto-sdk pre-commit` command.
> [xsoar.pan.dev] Update "Set Up Your Dev Environment" article

- docs/tutorials/tut-integration-ui.md
@Bharathwaj-Murali wrote in Slack (https://panw-global.slack.com/archives/C01225PADU1/p1736790008630149):
Can this docs be updated in this section https://xsoar.pan.dev/docs/tutorials/tut-integration-ui#integration-code to indicate that demisto.debug must be used to print debug logs? Using print statement can cause unexpected exceptions and errors.
https://panw-global.slack.com/archives/C011E5T5K17/p1715157686327079
I just had a customer report issue and they used print in the integration code. Replacing that with demisto.debug fixed the issue. Can we update the docs to ensure we have it noted?
> Add note about printing debug logs

- docs/integrations/debugging.md
Ready
Add additional info about using demisto.debug to print and then link to this from https://xsoar.pan.dev/docs/tutorials/tut-integration-ui#log-errors
> Add additional info about using demisto.debug to print

- docs/tutorials/tut-setup-dev.md
Ready
N/A
Adds note that poetry shell is no longer supported with poetry out of the box and requires a plugin according to poetry official docs. See: [https://python-poetry.org/docs/cli/#shell](https://python-poetry.org/docs/cli/#shell)
> Update Poetry instructions for tut-setup-dev.md

- docs/integrations/Trust-any-certificate.md
- sidebars.js
In Progress
fixes: [link to the issue](https://jira-dc.paloaltonetworks.com/browse/CIAC-13646)
add to our documentation the information about our insecure/verify parameter that we use from our baseClient http_request method.
> Trust Any Certificate Docs
