demisto/content-docs

docs/get-started.md
=> Fix button styling

docs/linting.md
=> Refactor long URL into markdown link

.github/ISSUE_TEMPLATE/developer-documentation-issue.md, .github/pull_request_template.md
Update the github issue and PR tempalates
=> Update issue and PR templates

docs/context-standards.md
Ready
Merge change from: https://github.com/demisto/content/pull/5186/files
=> update context standards

package-lock.json, package.json
Ready
fixes: #21 
Remove `browser-window`. This package doesn't seem to be used. Further more, the package is unmaintained from what it looks (it's the root cause for issue #21 ).
=> removing browser-window

docusaurus.config.js
Ready
Remove the author name from the last update at the bottom of the page
=> removed author from last update

docs/long-running.md
Ready
Update bullets that weren't displaying properly
=> update best practices bullets

docs/context-standards.md
Ready
relatedto: https://github.com/demisto/etc/issues/20829
Added context standards to "Account":
- TelephoneNumber
- Office
- JobTitle
- Department
- State
- Country
- City
- Street
- IsEnabled
=> Updated account context

src/theme/DocItem/index.js
Ready for review
Address formatting issue mentioned in #30 
Wrap the issue button in a row to prevent it from showing side-by-side with the "last updated" date.
=> Wrap issue button in row

docs/integration-docs.md
Ready
Update generate docs to use: DocumentationAutomation
=> docs generation to use: DocumentationAutomation

docs/playbook-contributions.md
Moved the contribution guide from docs to content-docs.
Ready
related to: https://github.com/demisto/etc/issues/17791
related to: https://github.com/demisto/content/pull/4918
Added a simplified playbook contribution guide for external and internal contributors.
View it here: 
https://github.com/demisto/content-docs/blob/6082198250a5ab2c315774ff6d0206424cc5871f/docs/playbook-contributions.md
=> Playbooks Contributions Guide

docs/howtos/integrations/unit-testing.md
Ready
Added common unit test use cases we usually use when writing integrations/scripts
=> added common unit test use cases

static/_redirects
Ready
Adding a redirect for for sign up 
=> sign-addn redirect

docusaurus.config.js
Ready
We were approved for a free Algolia docsearch scraper instance. The scraper will run every 24 hours which means we will no longer be responsible for running the scraper ourselves. 
=> Switch to Algolia docsearch index

static/_redirects
Ready
Added redirect from /docs to /docs/welcome
=> Added redirect from /docs to /docs/welcome

docs/integrations/docker.md
=> Remove an extra `not`

docs/integrations/package-dir.md
Ready
Update links to demisto-sdk repo docs
=> update links to demisto-sdk reference

docs/integrations/long-running.md
Ready
Small fix for a shorter sub title
=> shorten sub title

docs/integrations/packs-format.md
=> Update typo + broken link

docs/tutorials/tut-setup-dev.md
Updated Setup Tutorial with latest details
Ready
Updated Setup Tutorial with latest details: removed python 2, changed the path of HelloWorld pack
=> Updated Setup Tutorial with latest details

content-repo/gendocs.py
Ready
Fix for reference generation when integration has `?` in id. 
=> support for ? in id as seen in pwned v2

docs/integrations/integration-logo.md, docs/tutorials/tut-integration-ui.md
Ready
fixes: #80
Fix logo size 
=> update logo size 10kb

docusaurus.config.js
Ready
n/a
Disables typo tolerance on Algolia searches.
=> Disable typo tolerance on search

src/css/custom.css
Ready
related: https://github.com/demisto/content/pull/6309
Update video css. For displaying reference articles with videos from github.
=> css for video

README.md, content-repo/create-docs.sh, docs/integrations/doc-structure.md, docs/integrations/integration-docs.md
Ready
Added support to easily generate a local preview of the reference docs from a local directory of the content repo.
=> integration docs: how to preview locally

docs/tutorials/tut-integration-ui.md
Ready
fixes: #79 
Add note about code conventions.
=> Tutorial: add note about code conventions

content-repo/gendocs.py
Ready
Sidebar of reference section is now sorted ignoring case.
=> sort reference sidebar ignoring case

static/marketplace-index-mapping.json
Ready
Will be used to provide mapping of version to index
=> marketplace index mapping file

docs/integrations/code-conventions.md
Ready
Updated the code conventions page with the new CommandResults class. and return_results
=> update code conventions page

static/marketplace-index-mapping.json
Ready
Move to use base url and not full url to index
=> update mp index mapping

src/pages/index.js
Ready
See: https://lgtm.com/projects/g/demisto/content-docs/snapshot/46d892bc91295a42a03e3f5a612b00e37a82710a/files/src/pages/index.js?sort=name&dir=ASC&mode=heatmap#L124 
Removed unused variables from index.js
=> index.js: remove unused variables

docs/partners/development-partners.md, docs/tutorials/tut-setup-dev.md
Ready/
Broken link fixes in `tut-setup-dev`
=> fix broken links

docs/integrations/packs-format.md
=> Misc -> IndicatorTypes

docs/integrations/changelog-old-format.md, docs/integrations/changelog-old.md, docs/integrations/changelog.md, sidebars.js
Ready
fixes: Internal Change
Migration from Old RN format to New RN format required changes to docs.
=> Creation of documentation for new changelog format.

static/_redirects
Ready
Server will link to this redirect which we can update as we create more content about contributing.
=> redirect to start contributing

static/_redirects
=> Add office-hours to _redirects

docs/integrations/pycharm-plugin.md
Ready
We still didn't re-brand the plugin itself. Updated the instructions were relevant.
=> pycharm: update instructions to reference "Demisto Add-On"

docusaurus.config.js, src/css/custom.css
Ready
n/a
* Increase Algolia `hitsPerPage` to 1000
* Set fixed height on results listbox and set `overflow: auto` to enable scroll
n/a
=> Increase algolia hit limit and enable scroll

.github/config.yml
Ready
Welcome bot wasn't configured correctly for new issues.
=> fix welcome bot for new issue

.github/workflows/links-verify.yml
Ready
cron job to check site links. Will run daily.
Sample run can be seen here (before moving to cron job): https://github.com/demisto/content-docs/runs/706694694?check_suite_focus=true
=> Links verify

content-repo/extra-docs/releases/20.5.2.md
=> fixed SetGridByField changelog

content-repo/extra-docs/releases/20.5.3.md
=> 20.5.3 release notes

docusaurus.config.js
=> Updated Algolia Search

.github/workflows/links-verify.yml, content-repo/extra-docs/integrations/saml-okta.md, docs/integrations/getting-started-guide.md, docs/integrations/powershell-code.md, docs/tutorials/tut-integration-ui.md
Ready
Broken link fixes and added an exception to muffet
=> fix broken links and add exceptions to muffet

content-repo/extra-docs/articles/export-indicators.md, content-repo/extra-docs/articles/incident-lifecycle.md, content-repo/extra-docs/articles/minemeld-migration.md, content-repo/extra-docs/articles/tim-edl.md, sidebars.js, static/_redirects
Ready
Migrating non-dev docs to new articles section under the reference docs.
=> migrate to articles under reference docs

docs/integrations/parameter-types.md
=> Fix typos in parameter-types.md

docs/integrations/packs-format.md
Ready
Update structure docs according to our latest changes.
I wonder if we want to show `dependencies` and `displayImages` property in the example JSON.
=> Update pack_metadata docs

docs/integrations/packs-format.md
=> rm space pack metadata structure

docs/integrations/packs-format.md
Ready
Removing certification: certified
=> Most of the partners are not certified

content-repo/extra-docs/releases/20.6.0.md
=> 20.6.0 Release Notes

content-repo/extra-docs/releases/20.6.0.md
=> added Deep Instinct missing pack

docs/integrations/linting.md, docs/integrations/unit-testing.md, docs/tutorials/tut-setup-dev.md
Ready
fixes: https://github.com/demisto/content-docs/issues/171
=> Update lint cmd input from -d to -i

docs/integrations/integration-docs.md
Ready
Update how to work with video files and large media files.
=> Integration docs: updated usage of content-assets

docs/welcome.md
Ready
Welcome page had some empty sections. Removed empty sections and trimmed it down.
=> improvements to welcome page

content-repo/extra-docs/releases/20.6.1.md
=> 20.6.1 rns

content-repo/extra-docs/releases/20.6.1.md
Ready
We misplaced the xdr playbooks
=> move xdr playbooks to xdr - ir pack

docs/concepts/use-cases.md, docs/integrations/fetching-credentials.md, docs/integrations/getting-started-guide.md, docs/partners/become-a-tech-partner.md, docs/tutorials/tut-setup-dev.md
Ready
Updated old support portal links
there's still one (CLI article) that still looking for it in the panw support portal
=> Update old support portal links

docs/privacy.md, sidebars.js
Ready
Add privacy statement page.
=> add privacy statement

src/theme/DocItem/index.js
Ready
Change the create issue so the body is dynamic and contains links to source and site link.
=> create an issue where body contains links to site and source

content-repo/extra-docs/articles/microsoft-auth-guide.md
Ready
Fixed bullets and img format
=> Microsoft auth guide - fix format

content-repo/extra-docs/releases/20.7.0.md
=> 20.7.0 rns

content-repo/extra-docs/releases/20.7.0.md
Ready
TAXII 2 was released in 20.7.0, but this was not mentioned in the RN - added it in.
@yaakovi @jochman @glicht fyi
=> [Readme] Added taxii 2 release notes to 20.7.0 md

docs/integrations/yaml-file.md
Ready
Added docs about the `additionalDetails` field.
=> added additional field doc

.github/workflows/links-verify.yml, content-repo/gendocs.py
Ready
If we have too many errors fail the build (happened with Zimperium README which caused other readme files to fail).
=> fail when max errors are exceeded

docs/partners/office-hours.md, docusaurus.config.js
=> Office Hours page

Pipfile.lock, content-repo/gendocs.py, content-repo/gendocs_test.py, content-repo/mdx_utils.py
Ready
Increase timeout on mdx verification to be on the safe side.
=> Mdx timeout + pipenv update

.github/workflows/links-verify.yml, docs/integrations/dt.md
Ready
Small improvement to remove auto links in dt doc
=> remove links in dt

content-repo/extra-docs/releases/20.7.1.md
=> 20.7.1 Release Notes

docs/incidents/incident-classification-mapping.md
Ready
Added note how to set integration default classifiers and mappers
=> Integration default classifiers and mappers

content-repo/extra-docs/releases/20.7.2.md
=> added 20.7.2 rns

content-repo/extra-docs/articles/microsoft-auth-guide.md, docs/incidents/incident-classification-mapping.md
Ready
- Added note about self deployed param for Microsoft integration
- Fixed the integration default classifiers fields
=> Microsoft auth and classification docs improvements

docs/integrations/context-and-outputs.md
Ready
Added a note about illegal chars in context path and converted to md note
=> Context and Outputs - add note about illegal chars in context path

docs/incidents/incident-customize-incident-layout.md
Added video on how to convert layouts from 5.5 to 6
Ready
related to: https://github.com/demisto/content-assets/pull/2
Added a video to show how to convert Layouts
=> Added video on how to convert layouts to 6

docs/partners/why-xsoar.md, src/pages/index.js
Changing the demisto.com/integrations URL to new PAN site
=> New integrations URL

docs/integrations/context-standards.md
=> Corrected the Email.Attachment output

.github/workflows/links-verify.yml
=> Verify site links save log as artifact

docs/integrations/openapi-codegen.md, sidebars.js
Ready
Instructions for generating integrations using the open-api codegen tool.
=> OpenAPI code gen doc

docs/integrations/openapi-codegen.md
Fix spaces in the openapi-codegen doc and add pet store link
=> fix spaces

docs/integrations/packs-format.md
Ready
Added certification field documentation
=> pack_metdata_certification_field

docs/integrations/pycharm-plugin.md
=> Added playground requirement for running integrations

docs/playbooks/playbooks-create-conditional-task.md
Ready
fixes: https://github.com/demisto/content-docs/issues/249
=> Create a Conditional Task: fix typo

docs/integrations/openapi-codegen.md
Ready
No need for the title. We have a title which is added automatically. See:
=> Swagger code-gen: remove redundant title

.github/config.yml
Ready
The `Hello World` looks a bit weird, updated the welcome bot message
=> update bot welcome message

docs/integrations/context-and-outputs.md
Ready
Support multiple unique keys in CommandResults.
related to https://github.com/demisto/content/pull/8259
=> Support multiple unique keys in CommandResults

content-repo/extra-docs/releases/20.8.1.md, content-repo/gendocs.py
=> 20.8.1 Release Notes

content-repo/extra-docs/articles/microsoft-auth-guide.md
Ready
Add revoke consent section to microsoft auth article
=> Microsoft Auth Guide - add revoke consent section

content-repo/gendocs.py
Ready
Seen at: https://github.com/demisto/content-docs/pull/270 . Article failed generating but build succeeded.
=> fail build if articles or releases fail generating

docs/partners/development-partners.md
Ready
Removed link to `partner-owned-integration` as this page was removed.
=> Update development-partners.md - remove old link

docs/tutorials/tut-integration-ui.md
Ready
fixes: https://github.com/demisto/content-docs/issues/253
Add python 2/3 note
=> add python 2/3 note

content-repo/extra-docs/releases/20.9.0.md
=> 20.9.0 rns

docs/integrations/unit-testing.md
=> Update unit-testing.md - Typo

content-repo/extra-docs/articles/managing-credentials.md
Ready
related: https://github.com/demisto/etc/issues/27984
Clarify regarding credential caching
=> clarify credential caching

content-repo/extra-docs/articles/microsoft-auth-guide.md
Ready
reference: https://github.com/demisto/etc/issues/28202
=> ms_add_on_behalf_of_guide

docs/contributing/contributing.md, docs/integrations/getting-started-guide.md, docs/welcome.md
=> Fixed broken links

docs/integrations/mirroring.md
Ready
Remove xsoar mirroring example as it is not available yet.
=> mirroring: remove xsoar example

docs/integrations/packs-format.md
Dont want the support URL to be the main URL for the company.
=> Support URL fix

content-repo/extra-docs/articles/microsoft-auth-guide.md
Ready
Improve the On Behalf Of A User section under Self Deployed app
=> Microsoft Authentication - improve on behalf of a user section

docs/partners/become-a-tech-partner.md
=> Corrected training course names and loc

content-repo/extra-docs/releases/20.9.2.md
=> added 20.9.2 rns

docs/integrations/mirroring.md
Ready
Added that this command is being called when using the 'Select Schema' option.
=> Updated get-mapping-fields command description

docs/contributing/contributing.md
=> Enhancing contribution doc

docs/contributing/contributing.md
Ready
Added this as part of the feedback given regarding the need to push our partners to raise more issues related to XSOAR pltaform/SDK/etc.
=> Added slack info

docs/integrations/long-running.md
Ready
- Removed confusing text about `createIncidents`
- Add references to Demisto class docs
- Added new line before each image
=> Long Running - add reference to Demisto class docs

.circleci/config.yml, content-repo/post_github_comment.py
Ready
Small fixes to the build:
* use text when checking commit comment. See failure [here](https://app.circleci.com/pipelines/github/demisto/content-docs/34/workflows/af629ac7-6f0d-471f-8bd2-c9aae9519858/jobs/42).
* Preview link based on PR number as branch name may contain chars which are not good to include in the preview.
=> build fixes

content-repo/extra-docs/releases/20.10.0.md, content-repo/gendocs.py
=> 20.10.0 rns

docs/contributing/marketplace.md
Ready
fixes: https://github.com/demisto/content-docs/issues/340
Fixed typo
=> Marketplace article - fixed typo

docs/contributing/checklist.md
Ready
Add note to export single JSON files in checklist, and not a single JSON with all fields
=> Add note to export single JSON files in checklist

docs/partners/why-xsoar.md
=> Clean up of Why SOAR page

docs/integrations/dt.md
Description doesn't match the example
=> Fix, reference to Adobe, replace with urlscan.io

.github/workflows/build.yml
Ready
Fix so unit tests will run on forks
=> unit tests: run on forked pull_request

docs/integrations/fetching-incidents.md
=> fetching-incidents.md - fix LastRun example

docs/integrations/pack-docs.md
=> pack-docs.md - fix grammar

content-repo/extra-docs/articles/troubleshooting.md
=> fixed typos in troubleshooting guide

docs/integrations/packs-format.md
Ready
Add details about pack author image in the content pack structure article
=> Content Packs Structure - author image file

content-repo/extra-docs/releases/20.10.1.md
=> 20.10.1 rns

content-repo/create-docs.sh, docs/integrations/dev-setup.md
Ready
fixes: https://github.com/demisto/etc/issues/28220
=> added setup info about wsl2 performance and nodejs

.github/workflows/links-verify.yml, Pipfile, Pipfile.lock, content-repo/create-docs.sh, content-repo/gendocs.py, content-repo/gendocs_test.py
Ready
When building a PR there is no need to generate all the content docs unless infra scripts have changed. We limit to 20 random from each type.
Also limiting the number of release notes to 18 months back and provide a link to github for older release notes.
=> Optimized build for PR

docs/concepts/design-best-practices.md, docs/integrations/yaml-file.md
Ready
No where is it stated what our standards are for commands, arguments or outputs but it is something that we validate and heed.
=> Commands, Outputs and argument standards

content-repo/extra-docs/releases/20.11.0.md
=> 20.11.0-rns

docs/incidents/incident-classification-mapping.md
Ready
fixes: #375 
* Fix link to Integration configuration
* Use `jsonc` where we have json with comments
=> classification: fix link

content-repo/extra-docs/releases/20.11.0.md
Ready
Small fix to the release notes.
=> release notes 20.11.0 fix

content-repo/.gitignore, content-repo/create-docs.sh, content-repo/gendocs.py, content-repo/gendocs_test.py, docs/integrations/pack-docs.md
Ready
- reading approved usecases and tags list and adding them to the pack docs article
- improved indentation formatting for pack categories optional values
=> insert approved usecases and docs to pack docs article

static/_redirects
=> Add survey redirect for bd form

docs/integrations/context-and-outputs.md
Clarification about the value for the vendor name.
Ready
Add a note about the importance of integration_name matching name in the yml file.
=> Context doc: Vendor name clarification

docs/playbooks/generic-polling.md
Ready
Added a small explanation for the genericpolling timeout that comes up alot.
=> Added a note about genericpolling timeout

content-repo/extra-docs/releases/20.11.1.md
=> 20.11.1-rns

docs/integrations/mirroring.md
Ready
related to https://github.com/demisto/etc/issues/30696
Added docs for skip update during mirroring
=> Skip update on mirroring

content-repo/extra-docs/releases/20.12.0.md
=> 20.12.0-rns

docs/incidents/incident-jobs.md
Ready
fixes: https://github.com/demisto/content-docs/issues/396
=> Incident Jobs - fix TIM EDL job playbook article link

.github/workflows/links-verify.yml, content-repo/post_github_comment.py, content-repo/post_github_comment_test.py, docs/integrations/code-conventions.md, docs/integrations/context-standards-about.md, docs/integrations/package-dir.md
Ready
* Fixes. some broken links in our docs site.
* Also includes update to our doc ready notification to include links to the modified pages.
=> Broken link fixes

content-repo/gendocs.py, content-repo/gendocs_test.py
In Progress
fixes: https://github.com/demisto/etc/issues/30648
Added banner to documentation, where written : "Supported Cortex XSOAR versions: {from_version} and later."
=> Added Fromversion Banner

content-repo/extra-docs/releases/20.12.1.md
=> 20.12.1 rns

content-repo/post_github_comment.py, content-repo/post_github_comment_test.py
Ready
Notification didn't include the modified link when the front matter was too big. As can be seen here: https://github.com/demisto/content-docs/pull/417
=> fix notification with url changes

docs/tutorials/tut-setup-dev.md
Ready
Per some questions and mistakes, we see in the process ordered the flow a bit
=> Reordered the flow

docs/contributing/contributing.md
Ready
Added reference to branch creation
=> Added reference to branch creation

docs/tutorials/tut-design.md
=> Design Tutorial: fix borken link

docs/partners/adopt.md, docusaurus.config.js, sidebars.js
=> Add adopt pack page

content-repo/extra-docs/releases/21.1.0.md
=> release notes 21.1.0

docs/integrations/getting-started-guide.md, docs/welcome.md
Added references to newsletter sign up page
Ready
=> Added references to newsletter sign up page

docs/incidents/incident-classification-mapping.md
=> Typo fixes

content-repo/extra-docs/articles/troubleshooting.md
=> Fix link pointing to netlify build

docs/concepts/design-best-practices.md, docs/concepts/design.md, docs/tutorials/tut-design.md
Remove 'XSOAR' and 'Tutorial' from top level name
=> Update name on tut-design.md

docs/integrations/context-and-outputs.md
Ready
Added an example of CommandResults outputs with multiple IPs
=> Added example with multiple indicators in CommandResults

content-repo/extra-docs/releases/21.1.1.md
=> release notes 21.1.1

content-repo/extra-docs/articles/IAM-premium-pack-readme.md
Ready
Added demo video for ILM (IAM) pack
=> Added demo video for ILM (IAM) pack

content-repo/extra-docs/articles/CoA-premium-pack-readme.md
updated title to coa article
Ready
=> updated title to coa article

content-repo/extra-docs/articles/Shift management
In Progress
https://github.com/demisto/etc/issues/28569
Shift management and shift handover are crucial processes of SOC team management.
This pack's purpose is Provide a single interface for all those essential elements in one place in order to prevent loss of data in the shift handover process.
=> Shift management- pack documentation

content-repo/extra-docs/articles/Shift-management.md
=> Shift article fix

docs/integrations/yaml-file.md
=> Fixed wrong standard value

content-repo/extra-docs/articles/troubleshooting.md
Ready
related: https://github.com/demisto/etc/issues/33234
Following this comment: https://github.com/demisto/etc/issues/33234#issuecomment-770132183 added section about version revert.
=> troubleshooting: add info about reverting a version

content-repo/extra-docs/articles/microsoft-auth-guide.md
Ready
fixes: https://github.com/demisto/etc/issues/29054
=> MS Auth - add note about the redirect uri

docs/documentation/readme_file.md
=> Update readme_file.md: Fix broken link

content-repo/extra-docs/releases/21.2.0.md
=> Release notes 21.2.0

content-repo/extra-docs/articles/IAM-premium-pack-readme.md
Ready
* Updated the list of IAM compatible integrations.
* Added explanation to download the Workday pack in order to start working with the workday IAM integration
=> Updated ILM docs

.circleci/config.yml
Ready
Trying to fix the build. Installing netlify locally (not via sudo).
=> deploy: install netlify locally

content-repo/extra-docs/articles/Shift-management.md
=> Update Shift-management.md: Fix broken links

README.md
Ready
Update the top log to use the one from content.
=> Update README.md: update top logo to xsoar

.github/workflows/links-verify.yml, docs/contributing/contributing.md
=> Update contributing.md: fix broken link

.circleci/config.yml
Ready
Skip posting comments on daily deploy
=> post comment: skip on daily

content-repo/extra-docs/releases/21.2.1.md
=> release notes 21.2.1

docs/packs/premium_packs.md
Ready
fixes: https://github.com/demisto/content-docs/issues/497
New link https://docs.github.com/en/github/setting-up-and-managing-your-github-user-account/inviting-collaborators-to-a-personal-repository
=> fixed link

content-repo/gendocs.py, src/theme/DocItem/index.js
Ready
There is need to set the edit link to "null" so it is removed. Otherwise it uses a default.
=> prrmium docs: remove edit link

content-repo/extra-docs/articles/IAM-premium-pack-readme.md
=> Added link to Workday IAM integration

docs/contributing/marketplace.md
Ready
fixes: https://github.com/demisto/etc/issues/33113
Added a comment about the readme creation for new packs
=> Added a comment about the readme creation for new packs

docs/integrations/feeds.md
Ready
Document incremental feed option
=> feeds: incremental parameter

docs/contributing/marketplace.md, sidebars.js, static/_redirects
Ready
* Small change to the title of the contrib for the flow via Cortex XSOAR. 
* Adjusted redirect url from server to point to this page directly.
* Changed order of menu items
=> contrib: adjust redirect + page title

content-repo/extra-docs/releases/21.3.0.md
=> Release Notes 21.3.0

docs/integrations/debugging.md
Ready
fixes: #519
Rewritten debug document initial statement
=> Rewritten debug document initial statement

docs/contributing/contributing.md
Ready
Replace premium_packs broken link to `https://xsoar.pan.dev/docs/packs/premium_packs`
=> Fix broken link to premium packs

docs/integrations/context-standards-mandatory.md
Ready
add the category attribute to url context standard
=> Context Standards add category to url context standard

docs/integrations/docker.md
Ready
fixes: #404 
Add an advanced section to give more info on how the communication is done between server and docker.
=> docker doc: add advanced communication section

docs/integrations/unit-testing.md
Ready
Fix broken link to: https://docs.pytest.org/en/latest/how-to/parametrize.html and add `python` formatting to code blocks.
=> Update unit-testing: fix broken link + formatting

docs/integrations/yaml-file.md
=> Added a link to categories options from the yml basic information file

content-repo/extra-docs/integrations/googleapps-api.md
=> google apis: fix formatting

content-repo/extra-docs/articles/ransomware.md
=> Create Ransomware-readme.md (#478)

content-repo/extra-docs/releases/21.3.1.md
=> release notes 21.3.1

content-repo/extra-docs/articles/long-running-invoke.md
Ready
added note the integration instance name is case insensitive in the url
=> Long Running Invoke - added note about the instance name being case sensitive in the url

content-repo/extra-docs/articles/trust-custom-certificates.md
fixes: https://github.com/demisto/etc/issues/34417
=> Trust custom certificates

content-repo/extra-docs/releases/21.3.2.md
=> Release notes 21.3.2

content-repo/extra-docs/articles/splunk-add-on.md
Ready
Add description so it show up in the index.
=> splunk add-on add description

content-repo/extra-docs/articles/trust-custom-certificates.md
Ready
Add description so we have this in the articles index page.
=> custom certs add description

content-repo/extra-docs/articles/CoA-premium-pack-readme.md
Ready
Add article description so it shows up in the index
=> CoA pack add article description

content-repo/gendocs.py
Ready
* https://github.com/demisto/content-docs/pull/566
* https://github.com/demisto/content-docs/pull/565
* https://github.com/demisto/content-docs/pull/564
Fail the build of an article is missing a description. See related PRs for such cases. 
Build will pass once related PRs are merged.
=> articles validate: make sure description is present

docusaurus.config.js, genPackDetails.js, src/css/custom.css, templates/details.hbs
Ready
Restyles content table to better align things.
=> Fix content table styles

src/css/custom.css
Ready
Add filler to set min-width on content table.
=> Fix content table width

content-repo/extra-docs/articles/minemeld-migration.md
Ready
fixes: https://github.com/demisto/content-docs/issues/568
=> Update minemeld migration documentation

src/pages/marketplace/index.js
Ready/
Adds tag filtering to sidebar and URL query params.
=> Add tags filtering to menu and URL params

src/css/custom.css
Ready
Removes additional bottom margin between content and releases cards.
=> Fix table formatting

docs/contributing/checklist.md
Ready
added to the contrib checklist about the fromversion field for community packs
=> Contribution Checklist - add note about from version for community pack

genMarketplace.js
Ready
* Refactor to reduce duplicate code
* Addressed unused variable in changelog for loop
* Switch from `require()` to `fs.readFileSync()`
=> fix duplicate code, unused variables and switch to fs.readFileSync()

src/pages/marketplace/index.js
Ready
Removes unused code that resulted in build error.
=> Remove unused showFeatured code

content-repo/extra-docs/releases/21.4.0.md
=> release notes 21.4.0

docs/tutorials/tut-design.md
Ready
The link to the hello world design doc lead by mistake to the empty design doc. i fixed this
=> link to hello world design doc is fixed

content-repo/extra-docs/articles/Email-Communication-Readme.md
Ready
related: https://github.com/demisto/etc/issues/33997
related: https://github.com/demisto/content/pull/12183
Added to Email Communication pack the support of Microsoft Graph Mail after the command reply-mail was added.
=> add MS Graph Mail integration to Email Communication

src/css/custom.css, src/pages/marketplace/index.js, src/pages/marketplace/styles.module.css, templates/details.hbs
Ready
* Fix table formatting in details pages
* Only show integrations section in details pages if 1 or more integrations exist
* Reduce white space in marketplace view
* Change to approved brand font
* Change status colors to approved brand colors
=> Marketplace CSS and template adjustments

docs/concepts/faq.md
=> faq: update case the CLA status check is stuck

src/pages/index.js
Ready
Changed the "see all" link at the bottom of the landing page. @mchasepan feel free to suggest a different wording.
=> index page: change link to marketplace

content-repo/extra-docs/releases/21.4.1.md
=> release notes 21.4.1

docs/integrations/context-standards-mandatory.md
In Progress - will be changes after https://github.com/demisto/content/pull/12023 will be docs reviewed. 
related: https://github.com/demisto/content/pull/12023
related: https://github.com/demisto/etc/issues/34847
Adding fields to Endpoint.
=> Update Endpoints in context-standards-mandatory.md

docs/integrations/integration-cache.md
Ready
update the integration cache doc with the relevant wrapper funcs to use
=> Integration Cache - update with wrapper funcs

docs/integrations/integration-cache.md
=> Integration Cache - rm demisto class call

docs/integrations/context-standards-mandatory.md
In Progress
https://github.com/demisto/content/pull/12186
update the indicators context standard
=> update the indicators context standart

docs/partners/marketplace.md
=> Update marketplace.md broken  link

docs/integrations/long-running.md
=> long running: fix links to demisto-class

docs/contributing/contributing.md
Ready
https://github.com/demisto/etc/issues/28759
Improved docs.
=> Add contribution form filling to docs

docs/contributing/checklist.md
Ready
added the contrib checklist a note about fields association to specific types
=> Contribution Checklist - add note about fields association best practice

docs/integrations/unit-testing.md
Ready
Fix the link to example. As file name changed here: https://github.com/demisto/content/pull/12152
=> unit-testing page: fix example link

docs/partners/marketplace.md
=> partner marketplace doc: add link to the web version

content-repo/extra-docs/releases/21.5.0.md
=> release notes 21.5.0

docs/partners/marketplace.md, docusaurus.config.js, sidebars.js, src/pages/index.js
changing page name, conflicts w new /marketplace
=> Rename Partner marketplace page to Paid Packs

docs/concepts/getting-started-guide.md, docs/contributing/contributing.md, docs/partners/why-xsoar.md, docs/tutorials/tut-design.md
=> why xsoar: fix broken link

static/_redirects
temporary redirect from partners/marketplace to the new paid-packs page in case partners have old link
=> Update _redirects for paid-packs

content-repo/extra-docs/articles/long-running-invoke.md
=> long running invoke: add caution note

docs/integrations/scheduled-commands.md
Ready
https://github.com/demisto/content/pull/12280
Updated example in the docs to better suit the code used in Autofocus v2.
=> Updated scheduled command example

docs/playbooks/generic-polling.md
Ready
https://github.com/demisto/etc/issues/37246
=> Generic Polling - add max value to interval

content-repo/extra-docs/articles/long-running-invoke.md
=> Long Running Invoke - add note about no cert needed

docs/tutorials/tut-setup-dev.md
=> A few typos

docs/documentation/release-notes.md
Ready
Small clarifications and formatting updates + reference doc-review option.
=> release notes: clarifications + reference doc-review

src/pages/marketplace/index.js, src/theme/MarketplaceSidebar/index.js
Ready
* Refactors filtering logic for improved readability 
* Fixes issue with Marketplace sidebar that was preventing correct label from being displayed when starting from URL params filter 
=> Optimize filtering and handling of URL query params

docs/packs/packs-format.md
Ready
https://github.com/demisto/etc/issues/37322
Addded description for CONTRIBUTORS.md file
=>  Added description

docs/documentation/pack-docs.md
=> corrected typo

src/pages/marketplace/index.js
Ready
First attempt at updating pack filters based on clicking back and forward buttons in browser. Combines `useEffect()` and `history.pop` listener to set/unset state variables.
=> Update filters on history.pop

docs/welcome.md
Ready
We did a PR that changed the articles index link.
=> welcome page: fix link to articles

src/pages/marketplace/index.js
fixes: https://github.com/demisto/etc/issues/37885
Replace pack prices with 'PREMIUM'
=> Marketplace pan.dev - replace pack prices with 'PREMIUM'

src/pages/marketplace/index.js, src/theme/MarketplaceSidebar/index.js
In Progress
fixes: https://github.com/demisto/etc/issues/36827
* Added and removed query params from the URL when needed.
* Including @sserrata's [PR](https://github.com/demisto/content-docs/pull/664) - Refactors filtering logic for improved readability
=> Added URL query params support while using the sidebar filters

docs/integrations/postman-codegen.md
Added a tutorial video to the postman codegen documentation page.
=> Added video to postman code gen documentation

content-repo/extra-docs/articles/IAM-premium-pack-readme.md
Fixed broken link in  in Fields and Mappers section in Identity Lifecycle Management (ILM) documentation.
Ready
=> Fixed broken link

docs/documentation/pack-docs.md
Ready
https://github.com/demisto/etc/issues/38195
Edited 'Vunerability' to "Vulnerability'
=> Edited a typo

docs/tutorials/tut-design.md
=> a few corrections to wording and spelling

src/pages/marketplace/index.js, src/theme/MarketplaceSidebar/index.js
fixes: https://github.com/demisto/etc/issues/36827
description : Enables two-way synching between search input and URL query param q=.
=> Fix search query param to be displayed in the UI

docs/partners/become-a-tech-partner.md, docs/partners/why-xsoar.md
This is per request from PAN VP Alliances, TPT
=> add xsoar to names 

docs/concepts/demisto-sdk.md
Ready
fixes: https://github.com/demisto/etc/issues/37610
=> renamed GITHUB_TOKEN to DEMISTO_SDK_GITHUB_TOKEN

docs/concepts/demisto-sdk.md
Ready
fixes: https://github.com/demisto/etc/issues/37610
=> Added comment for changed get_remote_file behaviour

content-repo/extra-docs/releases/21.6.1.md
=> release notes 21.6.1

docs/concepts/demisto-sdk.md, docs/integrations/linting.md, docs/integrations/unit-testing.md
=> update lint section to include data about the coverage report

docs/concepts/demisto-sdk.md
Adding windows disclaimer for sdk usage
=> adding windows disclaimer for sdk

content-repo/extra-docs/articles/palo-alto-networks-cortex-xdr---investigation-and-response.md
Ready
Added the following playbooks to the article:
Cortex XDR - Delete file
Cortex XDR - Execute snippet code script
Cortex XDR - Run script
Cortex XDR - check file existence
Cortex XDR - execute commands
Cortex XDR - kill process
=> Added additional playbooks

content-repo/extra-docs/articles/Windows-Forensics-pack-readme.md
=> Windows Forensics documentation

src/pages/marketplace/index.js
Ready
fixes: https://github.com/demisto/etc/issues/38714
* Sorted the dropdown values in the marketplace sidebar
* Fixed file indentation
@sserrata FYI
=> Marketplace in pan.dev - Alphabeticaly order the dropdown menu values

content-repo/extra-docs/releases/21.7.0.md
=> release notes 21.7.0

docs/packs/packs-format.md
=> Correct typo and MIT lic text

docs/integrations/docker.md
Ready
Fixes a spelling typo
N/A
=> Fix spelling typo

content-repo/extra-docs/articles/managing-credentials.md
=> Link to deprecated vault integration

docs/documentation/readme_file.md
=> updating generated-docs docs

docs/concepts/design-best-practices.md
Ready
fixes: https://github.com/demisto/content-docs/issues/706
=> best-practices-typo

docs/concepts/pycharm-plugin.md
Ready
fixes: https://github.com/demisto/content-docs/issues/707
=> pychram-plugin-typo

docs/documentation/readme_file.md
Generate docs update - typo fixes
=> Generate docs update - typo fixes

docs/integrations/generic-commands-about.md
It was planned that the IAM commands documentation will be here and eventually it was put in another place
=> Remove IAM commands mention

content-repo/extra-docs/releases/21.7.1.md
=> 21.7.1 release notes

docs/concepts/demisto-sdk.md
https://github.com/demisto/etc/issues/33528
update the doc of upload command in demisto-sdk .md with the new option to upload zipped pack
=> Update doc for upload command with the upload zipped pack option

.circleci/config.yml
Ready
Trying to fix broken build
=> fix build: clear cache

docs/integrations/docker.md
=> docker.md: update section headers so they appear in side bar

docs/integrations/postman-codegen.md
Ready
https://github.com/demisto/etc/issues/38513
Added a description of newly feature of adding path variables from postman collection to code.
=> Update postman-codegen.md with Path variable addition

content-repo/extra-docs/articles/PS-Remote.md
=> PSRemote article link fix

docs/integrations/code-conventions.md
Ready
Added the supported version for hiddenusername configuration.
=> Add hiddenusername to code-conventions.md

content-repo/extra-docs/articles/Windows-Forensics-pack-readme.md
=> Windows Forensics fixed links

src/theme/MarketplaceSidebar/index.js
Ready/
Fixed broken link to the contributors page where the link came from: marketplace/
=> Fixed a bug in the contributors link

docs/documentation/pack-docs.md
fixes: https://github.com/demisto/etc/issues/39738
=> fix find-deps command

docs/concepts/concepts.md
Ready
fixes: https://github.com/demisto/content-docs/issues/732
=> fix-broken-links

content-repo/extra-docs/releases/21.8.0.md
=> Release Notes 21.8.0

docs/concepts/demisto-sdk.md
Ready
fixes: https://github.com/demisto/content-docs/issues/723
=> fix-typo-demisto

docs/integrations/docker.md
Ready
fixes: https://github.com/demisto/etc/issues/40034
=> auto-update-clarify

content-repo/extra-docs/articles/Phishing-Campaign.md
Ready
Fixes: https://github.com/demisto/etc/issues/38663
Related to: https://github.com/demisto/etc/issues/33810
Wrote an an article for the phishing campaign additions to phishing.
=> Article for the phishing campaign

docs/integrations/code-conventions.md
Ready
Adds a few examples for the credentials
=> Add examples for the credentials

content-repo/extra-docs/releases/21.8.1.md
=> Release notes 21.8.1

content-repo/extra-docs/articles/deprecated_info.json
Ready
Update deprecation note for edl management.
=> update deprecation for edl management

content-repo/extra-docs/articles/content-management.md
=> Content mgmt - Updated article

docs/integrations/custom-indicator.md
Ready
fixes: https://github.com/demisto/etc/issues/34971
Documentation for the new CustomIndicator type.
=> CustomIndicator doc

docs/integrations/code-conventions.md
=> Code conventions - fix url_keys typo in tableToMarkdown 

docs/playbooks/playbook-contributions.md
=> Playbook Contribution Guide  - fix demisto-sdk format cmd example

docs/tutorials/tut-design.md
Added a few corrections to this doc. please approve
=> design tutorial corrections

content-repo/extra-docs/articles/troubleshooting.md
Ready
Small note about pack install requirement.
=> troubleshoot: note about pack

docs/concepts/demisto-sdk.md
Ready
fixes: demisto/etc#33527
Making the `zip-packs` command public and update the documentation.
=> update readme with zip-packs command

content-repo/extra-docs/releases/21.8.2.md
=> release notes 21.8.2

content-repo/gen_top_contrib.py
Ready
Fixed error with None contributor.
Added support for 404 when user was not found.
=> Fixed None contributor - Contributors page

docs/integrations/package-dir.md
Ready
This PR should be merged after the next SDK release to accommodate this change: https://github.com/demisto/demisto-sdk/pull/1608
=> Update package-dir.md - split command name change

content-repo/extra-docs/articles/integrations-and-incident-health-check.md
Ready
Improve the configuration and setup instructions for Multi Tenant Environments for the `Integrations and Incidents Health Check` Pack.
If the Demisto API integration is configured at the child level it will throw an error when running the `!GetFailedTasks` command required in the main Job playbook.
=> Update Integrations and Incident Health Check Pack md

.circleci/config.yml
=> fix content-docs build

docs/partners/become-a-tech-partner.md
=> Update training link

docs/integrations/get-entries-filter.md
Ready
fixes: https://github.com/demisto/content-docs/issues/789
Removed duplicated field 'lastId'.
Fixed Descriptions.
=> Fix Get Entries Filter Documentation

content-repo/extra-docs/releases/21.9.0.md
=> release notes 21.9.0

src/pages/index.js
correct/update the size of our ecosystem and company!
=> Update numbers on main page

.circleci/config.yml, src/pages/marketplace/index.js
Ready
fixes: https://github.com/demisto/etc/issues/39235
Switches the corner triangles to fit the support.
=> Switches the corner triangles to fit the support

.circleci/config.yml
Ready
Trying to fix the build. Updated the version of the npm cache
=> update the cache version

content-repo/extra-docs/releases/21.9.1.md
=> release notes 21.9.1

src/pages/index.js
=> Add partner video to homepage

.circleci/config.yml, .firebaserc, .github/workflows/forked-pr-deploy.yml, content-repo/gendocs.py, content-repo/post_github_comment.py, docs/integrations/code-conventions.md, firebase.json, package-lock.json, src/pages/marketplace/slideshow.js
In Progress
fixes: https://github.com/demisto/etc/issues/42062
Moving the xsoar.pan.dev deployment from Netlify to Firebase
=> Move xsoar.pan.dev to firebase deployment

docs/contributing/marketplace.md
Ready
related: https://github.com/demisto/etc/issues/43304
Add a limitations section and add there that we are not supporting contributions to existing JS entities.
=> Added js-contrib limits

docs/concepts/faq.md
Javasript to JavaScript
Ready
N/A
Fixed typo - changed Javasript to JavaScript.
N/A
=> Fixed typo

firebase.json
=> Firebase conf - set trailingSlash to false

.circleci/config.yml
In Progress
Broken build: https://app.circleci.com/pipelines/github/demisto/content-docs/2793/workflows/b8edc6c5-0f00-4eff-a58a-77dcfe08cfee/jobs/4504
=> Revert to a previous pipenv version

content-repo/extra-docs/releases/21.11.0.md
=> Release notes 21.11.0

static/_redirects
Placeholder values for two URLs for private offer.
=> Add Private Offer Redirects

docs/concepts/demisto-sdk.md, docs/concepts/vscode-extension.md
Ready
fixes: https://github.com/demisto/content-docs/issues/857
Added a clarification to setup the environment variables.
=> Setup clarifications for demisto-sdk

firebase.json, static/_redirects
=> Private Offer Redirects placeholders

content-repo/extra-docs/releases/21.12.0.md
=> Release notes 21.12.0

content-repo/extra-docs/articles/microsoft-auth-guide.md
Ready
updated MS authentication doc
=> updated MS authentication doc

content-repo/extra-docs/articles/paloaltonetworks-integrations-overview
Ready
reference: https://github.com/demisto/etc/issues/44390
After the success of https://xsoar.pan.dev/docs/reference/articles/MS_Azure_Integrations, this PR aim to give a short overview and an entry point to PANW shop customers/SAs that maps to the integrated solutions we offer.
=> PaloAltoNetworks Integrations overview

docs/contributing/contributing.md
Ready
fixes: https://github.com/demisto/content-docs/issues/889
=> Contributing - fix link to support types doc

src/theme/ContentPackTabs/index.js, src/theme/ContentPackTabs/styles.module.css, templates/details.hbs
Ready
Moves the pack download button to a swizzled, custom `ContentPackTabs` component to better match the Tabs style.
=> refactor pack download button

content-repo/extra-docs/releases/21.12.1.md
=> Release notes 21.12.1

content-repo/extra-docs/packs/XSOAR-Content-Update-Notifications.md
Ready
Content Update Notification pack article
=> Content Update Notification pack article

docs/contributing/contributing.md
Ready
Added some important notes for contributors
=> updated contributing page

content-repo/extra-docs/articles/deprecated_info.json, content-repo/extra-docs/integrations/remote-access.md, content-repo/extra-docs/integrations/syslog.md, content-repo/gendocs_test.py, content-repo/mdx_utils.py, content-repo/post_github_comment_test.py, mdx-parse-server.js
Ready
* Fixed link to engine
* Added deprecated message
=> remote access +syslog: deprecate + fix link + change to XSOAR

content-repo/extra-docs/packs/Phishing-Alerts.md
Ready
Adding a reference to phishing v3 playbook in the Phishing Alerts article
=> Adding a reference to phishing v3 playbook

content-repo/extra-docs/articles/troubleshooting.md
Ready
https://github.com/demisto/etc/issues/37569
=> Troubleshooting - control read timeout via server conf

.circleci/config.yml
=> fixing build - clearing cache

docs/concepts/demisto-sdk.md
Ready
fixes: https://github.com/demisto/content-docs/issues/911
=> Demisto SDK - fix typo in env var

content-repo/extra-docs/articles/CI-CD-Article.md
Ready
fixes: https://github.com/demisto/etc/issues/45450
Added Migration Troubleshooting to handle validations errors.
=> [CI/CD Flow] Added Migration Troubleshooting

docs/indicators/url-extraction.md, sidebars.js
Ready
An article for the new URL extraction flow and components.
=> URL extraction documentation

content-repo/extra-docs/articles/setup-google-maps.md
=> [Documentation] Setup-google-maps.md

docs/contributing/marketplace.md
Ready
Update resubmission notes
=> Update resubmission notes

content-repo/extra-docs/integrations/saml_2.md
Ready
fixes: https://github.com/demisto/content-docs/issues/871
=> Update SAML 2.0 docs

docs/concepts/use-cases.md
=> vm-more-use-cases

content-repo/extra-docs/articles/splunk-add-on.md
Ready
Documentation added following this issue https://github.com/demisto/etc/issues/44432
Splunk add-on documentation about the error at the CIM was added.
=> Splunk docs CIM error added

.circleci/config.yml, build_utils/slack_notifier.py
Unified slack messages:
Scenarios (Note - there is no scenario where a build fails and the deploy passes since deploy requires the build) :
1. [Build fails](https://app.circleci.com/pipelines/github/demisto/content-docs/3481/workflows/d07bcf29-5544-4072-9bd6-3b7cb66b731a/jobs/5566):
2. [Build passes and deploy fails](https://app.circleci.com/pipelines/github/demisto/content-docs/3488/workflows/09067339-e2ed-49c4-b0cf-ee1b6d21d6e0/jobs/5580):
3. [Build and deploy pass](https://app.circleci.com/pipelines/github/demisto/content-docs/3489/workflows/079b38aa-f69f-47da-b03d-6126df4035a1/jobs/5586):
=> Unify slack messages

content-repo/extra-docs/articles/CI-CD-Article.md
Ready
N/A
Fixed typos and fixed indent level of Development so that it is inline with the other two high-level stages.
N/A
=> Fixed typos

content-repo/extra-docs/articles/troubleshooting.md
=> troubleshooting: add note about baseclient

docs/tutorials/tut-integration-ui.md
fix indentation on the new tutorial
=> yodaspeak indentation fix

docs/documentation/documentation_tips.md
Ready
fixes: https://github.com/demisto/content-docs/issues/955
=> Documentation Best Practices - rm wrong note about do not use by default instance

firebase.json
=> Final redirect for Private Offer learn more

docs/contributing/contributing.md
In Hold - pending opening the issues in the content repo as well as creating the proper label and opening the issues
=> Contributing - good first issue

docs/contributing/contributing.md, docs/contributing/demo-prep.md, sidebars.js
Ready
A new doc with explanation about the demo.
=> Contribution demo prep doc

docs/contributing/demo-prep.md
Ready
Docs review changes made.
=> docs review changes

content-repo/extra-docs/releases/22.2.0.md
=> Release notes 22.2.0

content-repo/extra-docs/articles/CI-CD-Article.md
Ready
fixes: https://github.com/demisto/etc/issues/46130
Added videos to the CI-CD Article.
=> Added videos to the CI CD Article

firebase.json
=> Update redirect for new sign-addn link

content-repo/extra-docs/articles/troubleshooting.md
Ready
Error seen at: https://github.com/demisto/etc/issues/47151
Add a common error to net troubleshooting
=> net troubleshoot: add another common error

content-repo/extra-docs/integrations/saml_2.md
Ready
fixes: https://github.com/demisto/content-docs/issues/993
Added description for the private key type
=> PKCS#1 type

docs/integrations/generic-commands-reputation.md
Added endpoint command to the generic-commands-reputation README file.
Ready
[fixes: link to the issue](https://github.com/demisto/etc/issues/44996)
Added endpoint command to the generic-commands-reputation README file.
=> Added endpoint command

docs/integrations/generic-command-endpoint.md
Ready
https://github.com/demisto/etc/issues/44996
Add generic endpoint command information
=> Add generic endpoint command

docs/concepts/demisto-sdk-docker.md, docs/concepts/demisto-sdk.md, docs/integrations/code-conventions.md
Ready
Readme for issue: https://github.com/demisto/etc/issues/45932
=> demisto-sdk docker readme

docs/integrations/generic-commands-reputation.md
Ready
Remove endpoint command from the Reputation commands.
=> Remove added endpoint command

content-repo/extra-docs/articles/Health Check.md
=> New article for System Diagnostics

content-repo/extra-docs/articles/microsoft-auth-guide.md
https://github.com/demisto/etc/issues/47307
Update screenshot and instructions for setting up an integration.
=> Update integration set up instructions

content-repo/extra-docs/articles/microsoft-auth-guide.md
Ready
fixes: https://github.com/demisto/etc/issues/46397
Add documentation regarding the option to use `Certificate Authentication` instead of using the `Client Secret`.
=> Add Microsoft Certificate Authentication

docs/integrations/dbot.md
In Progress
related to: https://github.com/demisto/etc/issues/39304
Used in case the API response is "not found"
c
=> Added 'Message' parameter to DBotScore

docs/integrations/code-conventions.md
In Progress
related to: [link to the issue](https://github.com/demisto/etc/issues/39304)
Function Description "create_indicator_result_with_dbotscore_unknown"
=> Function Description "create_indicator_result_with_dbotscore_unknown"

content-repo/create-docs.sh, content-repo/gen_top_contrib.py
Trying to fix build which is failing on github rate limiting from time to time. Such as here: https://app.circleci.com/pipelines/github/demisto/content-docs/4010/workflows/98d8c40a-afe9-4b74-b312-96adbc125e03/jobs/6381
=> gen top contrib: handle rate limiting

docs/integrations/scheduled-commands.md
Ready
https://github.com/demisto/etc/issues/47504e
Improve Scheduled Commands Documentation to Explain Empty Results 
=> Add How to Ignore Scheduled War Room Entries

content-repo/.gitignore, content-repo/gen_top_contrib.py
Ready
Looks like my previous fix didn't work. Adding small improvements.
=> fix top contrib retry backoff

docs/concepts/demisto-sdk-docker.md
=> demisto-sdk-docker typo

genMarketplace.js, templates/details.hbs
Ready
fixes: [ link to the issue](https://github.com/demisto/etc/issues/47848)
The link is working now for all the packs
=> fixing the the link to download packs in MP

content-repo/extra-docs/articles/troubleshooting.md
Ready
Added disclaimer about debug mode secret exposure risk. related to this https://github.com/demisto/etc/issues/47860
=> Added disclaimer

docs/integrations/test-playbooks.md
Ready
Just fixed the convention used for test playbooks from hyphen to underscore.
=> Fixed the convention used for a test playbook

docs/contributing/contributing.md
=> Update contributing.md about paloaltonetworks packs

docs/partners/become-a-tech-partner.md
add image of suggested timeline
=> Update become a tech partner page

docs/concepts/demisto-sdk.md, docs/integrations/yml-from-python-code-gen.md, sidebars.js
fixes: [link to the issue](https://github.com/demisto/etc/issues/48045)
=> Added documentation for generate-yml-from-python demisto-sdk command

src/css/custom.css
Ready
fixes: https://github.com/demisto/etc/issues/48140
After the fix:
=> Upodated xsiar logo

docs/integrations/code-conventions.md
fixes: https://github.com/demisto/content-docs/issues/1044
=> Command Runner documantation

docs/incidents/incident-lists.md
Ready
(https://github.com/demisto/etc/issues/44518)
New content items were introduced to content repo (Lists, Jobs, etc.). The new items should have documentation of the way they are presented under the pack's dir, the naming of the files, the files extensions, and the scheme they should be written by. This PR is for the Lists content item.
=> Add Lists content item topic

docs/partners/development-partners.md
=> fix error on Sciencesoft link

docs/packs/packs-format.md
relates to: https://jira-hq.paloaltonetworks.local/browse/XDR-52801
=> videos-add-prop

docs/documentation/pack-docs.md
relates to: https://github.com/demisto/content-docs/pull/1097, https://jira-hq.paloaltonetworks.local/browse/XDR-52801
=> video-prop-guidelines

.circleci/config.yml
Ready
Install the standalone firebase command.
=> build: add firebase-tools to dev dependencies

docs/documentation/release-notes.md
Ready
Updated the release notes wiki with the new standard.
=> Update Release Notes Guide

content-repo/extra-docs/articles/troubleshooting.md
Ready
Clarify debug-mode logs download for test module option.
=> Update debug-mode test module section

docs/documentation/release-notes.md
Reverts demisto/content-docs#1110
=> Revert "Update Release Notes Guide"

docs/integrations/api-execution-metrics.md
In Progress
Adding developer documentation for contributors to better understand how to implement the API Execution Metrics into their own integrations.
=> Add documentation for the API Metric Reporting feature

content-repo/create-docs.sh, content-repo/extra-docs/articles/deprecated_info.json
=> update deprecated: fix spelling mistake

docs/integrations/mirroring.md
Ready
Added information regarding mirroring parameters. (Not mandatory).
=> add optional params

docs/integrations/docker.md
Ready
fixes: https://github.com/demisto/content-docs/issues/1144
Addde description for base argument in create image docker command.
=> Added description for docker_image_create command

src/pages/marketplace/slideshow.js
Ready
fixes: [link to the issue](https://jira-hq.paloaltonetworks.local/browse/CIAC-3544)
Removing link to olf newsletter
FYI @mchasepan
=> remove old slide

docs/tutorials/tut-integration-ui.md
Ready
https://github.com/demisto/content-docs/pull/1152
For external schema support, added link to incident-classification-mapping#classify-using-a-classification-key
=> For external schema support added link

docs/incidents/incident-classification-mapping.md
Ready
Added External schema support in Step 3: Load event data using one of the following options:
=> Add External schema support info

docs/packs/packs-format.md
Ready
Added the hidden key to the pack metadata file
=> Added the hidden key to the pack metadata file

docusaurus.config.js
=> Correct blog url

content-repo/extra-docs/articles/troubleshooting.md
Ready
Provide example on how to config host networking for only a specific docker image.
=> update troubleshooting - docker image specific config example

build_utils/slack_notifier.py
Ready
fixes: https://jira-hq.paloaltonetworks.local/browse/CIAC-3102
updating the notification slack channel
=> Update Slack Channel

docs/concepts/design.md
update the links for new template and new example of design document
=> update design page

docs/integrations/yaml-file.md
Ready
fixes: https://github.com/demisto/demisto-sdk/pull/2262
Describing the possible values for the `hidden` parameter attribute.
=> possible `hidden` parameter attribute values

content-repo/gendocs.py, content-repo/gendocs_test.py
Ready
fixes: https://jira-hq.paloaltonetworks.local/browse/CIAC-3572, https://jira-hq.paloaltonetworks.local/browse/CIAC-3794
create link to a pack only for xsoar marketplace
=> Do not create a marketplace link for XSIAM packs 

docs/documentation/release-notes.md
will be merged when SDK v1.7.3 is out
[SDK PR](https://github.com/demisto/demisto-sdk/pull/2285)
=> added `Added a`, `Added an` RN templates

content-repo/extra-docs/packs/Email-Communication-Readme.md
related: https://jira-hq.paloaltonetworks.local/browse/CIAC-2068
Added the reply-mail commands to EWSO365 and gmail single user. therefore, added to the article that those integrations are now part of the email communication pack
=> added integrations to article

content-repo/gendocs.py, content-repo/gendocs_test.py
Ready
fixes: https://github.com/demisto/content-docs/issues/1182
Do not create a link to the marketplace for XSIAM content entities
=> Do not create links to a pack in xsiam playbooks

content-repo/gendocs.py
=> Updated the max failures to 20

content-repo/extra-docs/packs/content-management.md
Updated several links that were returning 404 with the correct URL.
=> Update links to doc_files with correct URL

docs/tutorials/tut-setup-dev.md
=> tut-setup: fix broken link

content-repo/extra-docs/articles/Doc-Create-XSOAR-Incident-from-MS-Form-Submission.md
Ready
New doc to add to Dev Site Articles: Creating a Cortex XSOAR incident from an MS Form Submission
=> Create an XSOAR incident from MS Form Submission

firebase.json, src/pages/marketplace/index.js
Ready
Since the contributor's page is based on. the create docs script which is not in the new repository of the marketplace
We should disable the redirect for the contributors page
=> disable Contributions redirect

content-repo/extra-docs/packs/Malware_Investigation_&_Response.md
Ready
improvements for Malware Investigation And Response article
=> article improvements

content-repo/gendocs.py
Ready
increasing the MAX_FAIL env
=> increase the max failure

docs/integrations/parameter-types.md
Ready
fixes: [link to the issue](https://github.com/demisto/content-docs/issues/1235)
Added the parameter type number in the parameter type page
=> Add the parameter type number

content-repo/extra-docs/packs/Email-Communication-Readme.md, docs/documentation/release-notes.md
Ready
Fixed broken pics and re-ordered the document.
=> Fixed broken pics and re-ordered the document.

docs/integrations/code-generator.md
Ready
https://github.com/demisto/content-docs/issues/1211
Update the info for the Integration config json file
=> Update the info for the Integration config json file

content-repo/extra-docs/articles/aws-auth-guide.md
Ready
Relates: [link to the issue](https://jira-hq.paloaltonetworks.local/browse/CIAC-4586)
=> Update aws auth guide about connection with Session Token

docs/documentation/release-notes.md
Ready
https://github.com/demisto/demisto-sdk/pull/2506
I've updated the prefix list adding the newly approved ones.
=> Updated prefix list

content-repo/gendocs.py, content-repo/gendocs_test.py, docs/documentation/pack-docs.md
=> Added support for marketplace-specific tags

content-repo/extra-docs/articles/CI-CD-Article.md
https://jira-hq.paloaltonetworks.local/browse/CIAC-4598
Adding a documentation on how to manage a pull request in CI/CD playbook, how to create and update a pull request in this option.
=> Added documentation on how to manage a pull request in CI/CD playbook

.github/workflows/codeql.yml, content-repo/gendocs.py
Ready
fixes: https://jira-hq.paloaltonetworks.local/browse/CIAC-4727
Added CodeQL to GitHub actions since LGTM is EOL.
=> Add code ql workflow for git hub code scanning

content-repo/extra-docs/articles/microsoft-auth-guide.md, content-repo/extra-docs/packs/Email-Communication-Readme.md
In Hold until this epic is done https://jira-hq.paloaltonetworks.local/browse/CIAC-3650
https://jira-hq.paloaltonetworks.local/browse/CRTX-59566
following the above issue, added a security alert for the device code flow
=> security alert for device code

content-repo/extra-docs/articles/aws-auth-guide.md
Ready
Fixed an issue in the documentation
=> AWS Integrations - Authentication

content-repo/extra-docs/articles/microsoft-auth-guide.md, content-repo/gendocs.py
=> ms integrations: improve security awareness note

docs/integrations/code-conventions.md
After a meeting we had discussing recent and common questions around the XSAOR pagination standards, a few baselines were established to make this topic more accessible.
=> Update Pagination standards section

content-repo/extra-docs/articles/aws-auth-guide.md
Ready
After a call with a client, the bug they experienced with AWS was solved by changing a definition with the docker communication. we added this info to our documentation to help others in the future who might experience the same issue. https://jira-hq.paloaltonetworks.local/browse/XSUP-20467
=> update aws docs

content-repo/extra-docs/articles/splunk-add-on.md
Ready
added instructions for using xsoar v8 with splunk add on
=> added instructions for using xsoar v8 with splunk add on

content-repo/extra-docs/articles/microsoft-auth-guide.md
https://jira-hq.paloaltonetworks.local/browse/CIAC-1008
added a new section describe the Azure Managed Identities
=> update doc with managed identities

content-repo/extra-docs/articles/microsoft-auth-guide.md
https://jira-hq.paloaltonetworks.local/browse/CIAC-1268
replace the old documentation regarding the Auth flow
=> Update doc with the new Microsoft login url generator

content-repo/extra-docs/articles/microsoft-auth-guide.md
- Fix the auth code flow section 
- Update the supported flows table with the Auth code in Microsoft Teams
=> Update Microsoft auth doc

content-repo/extra-docs/packs/integrations-and-incident-health-check.md
Ready
fixes: https://jira-hq.paloaltonetworks.local/browse/XSUP-20349
Added a note to the documentation that integrations that are configured with the `Do not use by default` checkbox will not be tested.
=> Health Check DeafultIgnore Note

docs/integrations/code-conventions.md
Add example for 'next_token' in context, and fix title.
=> Update Pagination Standard

docs/integrations/scheduled-commands.md
Adding a note about the use of the PollResult Class argument: arg_to_next_run
=> Update scheduled-commands.md 

docs/documentation/release-notes.md
Proposing explanations for the versioning types.
Would appreciate your input.
=> Propose versioning types explanations

docs/integrations/yml-from-python-code-gen.md
fixes: [link to the issue](https://jira-hq.paloaltonetworks.local/browse/CIAC-3029)
Fixing docs for defaults in generate-yml-from-python.
=> Fixing docs for defaults in generate-yml-from-python

content-repo/extra-docs/integrations/googleapps-api.md
Ready
fixes:  https://github.com/demisto/content-docs/issues/1311
Fixed typo in google apps API `gamil` -> `gmail`
=> Fix typo in google apps api

content-repo/gendocs.py
Ready
Increasing the max failures.
=> Increase max failures

.github/workflows/build.yml, .github/workflows/links-verify.yml, content-repo/extra-docs/articles/aws-auth-guide.md
Ready.
related: https://github.com/demisto/content/pull/25681
=> added AWS PrivateLink docs

docs/tutorials/tut-setup-dev-remote.md
fixes: https://github.com/demisto/content-docs/issues/1299
=> Fix VSCode devcontainer image

docs/concepts/demisto-sdk.md
fixes: https://jira-hq.paloaltonetworks.local/browse/CIAC-4469
=> improved sdk upload doc

content-repo/gendocs.py
=> decrease max failure

content-repo/extra-docs/articles/microsoft-auth-guide.md
Ready
fixes: [[Azure Active Directory Identity And Access] Add certificate authentication](https://jira-hq.paloaltonetworks.local/browse/CIAC-6140)
[[Azure Active Directory Groups] authorization_code support](https://github.com/demisto/content/pull/24698)
=> [Microsoft] Update supported Authentication Flows for Microsoft integrations

docs/integrations/code-conventions.md
Ready
Added the key to the table along with the data needed.
=> Add `relationships` key to `CommandResults` object

content-repo/create-docs.sh, content-repo/extra-docs/scripts/commonserveruserpowershell.md, content-repo/extra-docs/scripts/commonserveruserpython.md, content-repo/extra-docs/scripts/commonuserserver.md
Add CommonServerUser docs to 'extra-docs' after removing them from Content on https://github.com/demisto/content/pull/27311
=> Add CommonServerUser Scripts

content-repo/extra-docs/articles/Default Pack.md
Ready
Related to: https://github.com/demisto/content-docs/pull/1348
Added screenshots of the incident layout to the article about the Default pack.
=> Updated the Default article with more images

content-repo/extra-docs/packs/content-management.md
fixes: [link to the issue](https://jira-hq.paloaltonetworks.local/browse/CIAC-5218)
=> Migration Guide from Dev-Prod to CI/CD

docs/tutorials/tut-integration-ui.md
Ready
https://github.com/demisto/content-docs/pull/1353
Fixed wrong single quote change from `’` to `'`
=> Fixed single quote tut integration

content-repo/extra-docs/articles/microsoft-auth-guide.md
In Progress
relates: https://jira-hq.paloaltonetworks.local/browse/CIAC-818
Adding a table indication support of National Clouds in Microsoft integrations.
=> Microsoft usgov support

content-repo/create-docs.sh, content-repo/gendocs.py
Ready
Added the current branch as an argument in the generate_docs script, since the `CURRENT_BRANCH` env is None.
See this [commit](https://github.com/demisto/content-docs/pull/1358/commits/f9d85ebeb9e57ee9ceab20a413be759f18c6a608) and this [build](https://app.circleci.com/pipelines/github/demisto/content-docs/6040/workflows/55f46a48-38f8-4877-ad72-948ed5af053d/jobs/9756?invite=true#step-108-2780)
=> generate_docs  added the branch name as script arg

content-repo/extra-docs/packs/content-management.md
Ready
fixes: [link to the issue](https://jira-hq.paloaltonetworks.local/browse/XSUP-23689#:~:text=%3C-,%2D%2D%2D%2D,-We%20managed%20to)
https://github.com/demisto/content/pull/27859
=> [Content Management - Delete Custom Content] Update the new input - `instance_name`

docs/concepts/vscode-extension.md, docs/tutorials/tut-setup-dev.md
=> vscode extension updates

.circleci/config.yml, build_utils/slack_notifier.py
fixes: [link to the issue](https://jira-hq.paloaltonetworks.local/browse/CIAC-6882)
Added the errors count to the Slack notifier
=> [Content docs nightly slack notifier] Added the errors count

docs/documentation/release-notes.md
Ready
Related PR: https://github.com/demisto/demisto-sdk/pull/1944
removed the `- Maintenance and stability enhancements.`
=> removed `- Maintenance and stability enhancements.`

docs/integrations/fetching-credentials.md
relates: https://jira-hq.paloaltonetworks.local/browse/XSUP-26418
=> fetching-credentials Return Value

docs/integrations/unit-testing.md
fixes:  https://jira-hq.paloaltonetworks.local/browse/CIAC-3838
https://jira-hq.paloaltonetworks.local/browse/CIAC-7635
All the pip and pipfile.lock files have been deleted from the content repository, there is no need for the *Setup Pipenv* section anymore.
=> delete pip section

content-repo/gendocs.py, content-repo/ignored_entities.json
Ready
fixes: https://jira-hq.paloaltonetworks.local/browse/CIAC-7997
Added a new file `ignored_entities.json` which allows skipping content entities from processing and display them on the website.
=> Added config file in order to ignore content entities from processing and display in the website

docs/concepts/demisto-sdk.md, docs/contributing/sdk.md
Ready.
fixes: https://jira-hq.paloaltonetworks.local/browse/CIAC-8356.
Add SDK contribution document under _Developer Docs > Contributing > SDK_.
=> SDK Contributions

content-repo/extra-docs/articles/microsoft-auth-guide.md
=> Microsoft updated docs

docs/integrations/fetching-incidents.md
Ready
As requested, used the correct name of the parameter.
=> Change to incidentFetchInterval parameter

docs/playbooks/playbook-conventions.md
Ready
https://jira-hq.paloaltonetworks.local/browse/CRTXDOC-1998
A playbook name cannot contain the following special characters.
Punctuation marks: ! " # $ % & ' ( ) * + , . / : ; < = > ? @ [ \ ] ^ ` { | } ~
Symbols: © ® ™ ° µ ± ß
Formatting characters: ¶ §
=> Playbook name - no special characters

docs/documentation/images_in_documentation_files.md, docs/documentation/integration-description.md, docs/documentation/readme_file.md, sidebars.js
Ready
https://jira-hq.paloaltonetworks.local/browse/CRTXDOC-1987
Created a new topic for images in documentation file.  
In the README topic, removed the Images section and instead created a link to the new images in documentation files topic. 
In the Integration Description File topic, added an Images section with a link to the new images in documentation files topic. 
=> New topic in Pan Dev - Images in Doc Files

docs/documentation/integration-description.md, docs/documentation/readme_file.md
Ready
https://jira-hq.paloaltonetworks.local/browse/CRTXDOC-1987
Broken link in Images section
=> Fix broken link

sidebars.js
Ready
fixes: https://jira-hq.paloaltonetworks.local/browse/CIAC-8356
Add the SDK contribution instructions to the _Developer Docs > Contributing_ sidebar as it was missed from https://github.com/demisto/content-docs/pull/1392. 
Before:
After:
=> Added SDK to Developer Docs Sidebar

docs/documentation/integration-description.md
Ready
fixes: [link to the issue](https://jira-dc.paloaltonetworks.com/browse/CIAC-8452)
add `supportlevelheader` documentation
=> add supportlevelheader to docs

content-repo/extra-docs/articles/microsoft-auth-guide.md
=> updated docs

docs/integrations/code-conventions.md
Internal pr for https://github.com/demisto/content-docs/pull/1408
=> Use correct key for Contents (#1408)

content-repo/extra-docs/articles/splunk-add-on.md
Ready
fixes: https://github.com/demisto/content-docs/issues/1398
=> Splunk add-on fix typo

docs/integrations/context-standards-mandatory.md
Ready
fixes: https://jira-dc.paloaltonetworks.com/browse/CIAC-9113
Added a missing YAML section for Rule.
=> Add Context Output for Rule YML

.npmrc
Ready
Temporary increseing the node memory size untill this [PR](https://github.com/demisto/content-docs/pull/1433) will merged
=> increase node memory size

docs/contributing/sla.md
Ready
Added an explanation to the contribution SLA page regarding adding or updating aPR after the initial review.
=> Added Documentation Regarding Adding or Updating a PR after the Review

content-repo/extra-docs/articles/Health Check.md, content-repo/extra-docs/integrations/saml-adfs.md, content-repo/extra-docs/packs/Email-Communication-Readme.md, content-repo/extra-docs/packs/Rapid-Breach-Response.md, content-repo/extra-docs/packs/SystemDiagnosticsHealthCheck.md, content-repo/extra-docs/packs/integrations-and-incident-health-check.md, content-repo/extra-docs/packs/palo-alto-networks-cortex-xdr---investigation-and-response.md, docs/incidents/incident-lists.md
fixes: https://jira-dc.paloaltonetworks.com/browse/CIAC-9102
The Demisto REST API integration has been deprecated. Use the Core REST API integration in its place. The functionalities are the same.
=> [Demisto REST API ] updated docs

docs/contributing/contributing.md
=> fix misspelled word

.github/auto_assign-issues.yml
Ready
fixes: https://jira-dc.paloaltonetworks.com/browse/CIAC-8978
Added a github config (according to [this](https://github.com/apps/auto-assign-issues) documentation) to automate assign issue to @ShirleyDenkberg and @richardbluestone 
=> Auto assign issue

docs/partners/adopt.md
=> fix a bug in adoption process

docs/contributing/contributing.md
=> Update hello world doc

docs/documentation/release-notes.md
Ready
Specify that breaking changes notes field can be in HTML/Markdown format and provide an example.
=> Add Breaking Changes supported formats and example

docs/documentation/pack-docs.md
Related: https://jira-dc.paloaltonetworks.com/browse/CIAC-5348
Align pack categories with `Tests/Marketplace/approved_categories.json`
https://xsoar.pan.dev/docs/documentation/pack-docs#pack-keywords-tags-use-cases--categories
=> [Pack Documentation] Update Pack Categories

docs/integrations/mirroring.md
Ready
fixes: https://jira-dc.paloaltonetworks.com/browse/CIAC-9640
Added troubleshooting section for recurring problems.
=> Add Mirroring Troubleshooting Section

content-repo/gendocs.py
In Progress
fixes: https://jira-dc.paloaltonetworks.com/browse/CIAC-9910
Skip generation of Premium Packs docs.
=> ignore generate private docs

content-repo/extra-docs/articles/aws-auth-guide.md
Ready
fixes: https://github.com/demisto/content-docs/pull/1245
=> Fixed AWS authentication options

docs/integrations/yaml-file.md
Ready
related https://github.com/demisto/etc/issues/40981
Add `fromlicense`  To The Parameter Table
=> [yaml-file] Add `fromlicense`  To The Parameter Table

content-repo/extra-docs/packs/Phishing-Campaign.md
Ready
Related to: https://jira-dc.paloaltonetworks.com/browse/XSUP-34760
Improved the documentation to state where the pack is being used and where it is not available.
=> Phishing Campaign - document which platforms are supported

docs/contributing/sdk.md
Ready
fixes: https://jira-dc.paloaltonetworks.com/browse/CIAC-10019
* Update https://xsoar.pan.dev/docs/contributing/sdk to use the new `sdk-changelog` tool to create a changelog entry.
* Update CI checks to GitHub.
=> Update Changelog Instructions/GitHub Actions

docs/integrations/mirroring.md
Ready
There were several bugs regarding switching between different mappers (mostly between a custom with out of the box one), the customers don't understand why it is not working after the switch. I added this clarification, so that the customers will now what to do to make the switch work.
=> A clarification about mappers

docs/integrations/mirroring.md
Ready
Describing mirroring behavior for closed incidents.
=> Adding closed incident mirroring behavior hints

docs/integrations/yaml-file.md, docs/packs/packs-format.md
=> Add Marketplaces

docs/contributing/marketplace.md
In Progress
fixes: https://jira-dc.paloaltonetworks.com/browse/CIAC-10496
* Update step 3 to complete contribution form to be present tense to align with step 1.
* Remove incorrect note.
* Add [information admonition](https://docusaurus.io/docs/markdown-features/admonitions) for how to contribute an existing content item.
=> Update MP Contribution to Existing Pack

content-repo/extra-docs/articles/download-packs-and-docker-images-offline.md, docs/partners/adopt.md
=> path changes for scripts used by contributors

docs/documentation/readme_file.md
Ready
typo and lightened wording
cf diff tab
=> readme_file.md: typo and lightened wording

content-repo/create-docs.sh, content-repo/gen_pydocs.py
Ready
fixes: [link to the issue](https://jira-dc.paloaltonetworks.com/browse/CRTXDOC-3033)
Do not escape html characters in doctoring
[fixed link](https://xsoar-pan-dev--pull-request-1574-5s7uymmh.web.app/docs/reference/api/demisto-class#incident)
Before fix:
After fix:
=> fixed HTML characters in demisto mock

docs/playbooks/playbooks-overview.md
Ready
fixes: [link to the issue](https://github.com/demisto/content-docs/issues/1584)
=> Fix typo in playbook docs

docs/documentation/pack-docs.md
Ready
Updated the list according to [this](https://github.com/demisto/content/blob/master/Tests/Marketplace/approved_categories.json) file
=> update pack categories

content-repo/create-docs.sh, docs/packs/packs-format.md
fixes: https://jira-dc.paloaltonetworks.com/browse/CIAC-10674
=> changed approved files path

content-repo/extra-docs/articles/microsoft-auth-guide.md
fixes: [link to the issue](https://jira-dc.paloaltonetworks.com/browse/XSUP-40035)
Added Authorization Code flow Troubleshooting
=> Microsoft docs - added Authorization Code flow Troubleshooting

content-repo/extra-docs/articles/microsoft-auth-guide.md
fixes: [link to the issue](https://jira-dc.paloaltonetworks.com/browse/CIAC-6383)
Updated the Supported Authentication Flows for Microsoft integrations
=> Microsoft - update table

docusaurus.config.js
Ready
Removed unsupported type attribute (revert of [this](https://github.com/demisto/content-docs/pull/168) PR)
=> Remove Algolia options

docusaurus.config.js
Ready
revert this PR https://github.com/demisto/content-docs/pull/1595
=> Revert Algolia options

.npmrc
Ready
fixes: https://panw-global.slack.com/archives/C03A9TJ57FT/p1723439708118569
Increased JS memory to 13 GB
=> Increased JS memory to 13 GB

docs/integrations/context-standards-recommended.md
Ready
Related: [link to the issue](https://jira-dc.paloaltonetworks.com/browse/CIAC-11252)
Added details about the manager in the Account.
=> [Account] Add Manager details

content-repo/ignored_entities.json, content-repo/mdx_utils.py
fixes: [link to the issue](https://jira-dc.paloaltonetworks.com/browse/CRTXDOC-3987)
Update normalized ID function so it will allow underscore in the ID.
=> Exclude Netskope (API v2) integration

.gitlab/ci/.gitlab-ci.yml
=> fix CURRENT_BRANCH_NAME

.github/workflows/build.yml, .github/workflows/codeql.yml, .github/workflows/links-verify.yml, content-repo/extra-docs/packs/content-management.md
Ready
fixes: https://jira-dc.paloaltonetworks.com/browse/CIAC-12915
Updated GitHub checkout action to version 4
=> increase the checkout action version to 4

.npmrc
=> Increase Node JS heap size to 30 GB

.github/workflows/build.yml, content-repo/gen_top_contrib.py
=> Improved get top contrib script

.gitlab/ci/.gitlab-ci.yml, content-repo/gendocs.py, content-repo/mdx_utils.py
=> Fixed mdx verify read timeout and improve ignored files

.gitlab/ci/.gitlab-ci.yml, .npmrc
=> Increase memory to 45 GB

content-repo/create-docs.sh, src/css/custom.css
=> add new list style

.github/workflows/auto-assign-issues.yml
=> Remove Shirley from assigned issues
